In [72]:
import numpy as np

v1 = np.array([1,2,3])
v2 = np.array([1,-1,1])
 
print(v1 + v2)

[2 1 4]


In [73]:
v3 = 4*v2
v3
print(np.linalg.norm(v3))

np.linalg.norm(v2)

6.928203230275509


1.7320508075688772

In [74]:
np.dot(v2,v3)

12

In [80]:
#Matrix
p = np.array([[20,7],[2,1],[6,2]])
q = np.array([[1,2],[1,-8],[1,1]])
# print(np.add(p,q))
# print(p+q)
# print(np.subtract(p,q))
# print(p-q)
q = np.transpose(q)
value =np.linalg.det(np.dot(p,q))
# print(value)


mat = np.dot(p,q)
print(mat)
invmat = np.linalg.inv(mat)
print(np.matmul(mat,invmat))

[[ 34 -36  27]
 [  4  -6   3]
 [ 10 -10   8]]
[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0. -4. -8.]]
